/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlvinBlog: typeof import('./src/components/AlvinBlog.vue')['default']
    EduardoBlog: typeof import('./src/components/Eduardo/EduardoBlog.vue')['default']
    EduardoPosts: typeof import('./src/components/Eduardo/EduardoPosts.vue')['default']
    FooterBar: typeof import('./src/components/shared/FooterBar.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/shared/TopBar.vue')['default']
  }
}
